import { IDiff } from '../../../shared/types/diff.types';
import { TEntityId } from '../../../shared/types/uuid';

export const ECategoryStatus = {
  Active: 'active',
  Archived: 'archived',
} as const;

export type UCategoryStatus =
  (typeof ECategoryStatus)[keyof typeof ECategoryStatus];

export interface ICategory {
  id: TEntityId;
  accountingEntityId: TEntityId;
  accountId: TEntityId;
  accountMaterializedPath: string;
  version: number;
  status: UCategoryStatus;
  name: string;
  isGrouping: boolean;
  createdAt: Date;
  updatedAt: Date;
  deletedAt: Date | null;
}

export const ECategoryHistoryAction = {
  Created: 'created',
  Updated: 'updated',
  Archived: 'archived',
  Unarchived: 'unarchived',
} as const;

export type UCategoryHistoryAction =
  (typeof ECategoryHistoryAction)[keyof typeof ECategoryHistoryAction];

export interface ICategoryHistory {
  // NB: serial id will be generated by the persistence layer
  categoryId: TEntityId;
  userId: TEntityId;
  action: UCategoryHistoryAction;
  diff: IDiff<ICategory>;
  note: string | null;
  createdAt: Date;
}
