import { IDiff } from '../../../shared/types/diff.types';
import { TEntityId } from '../../../shared/types/uuid';

export interface ICategory {
  id: TEntityId;
  accountingEntityId: TEntityId;
  accountId: TEntityId;
  version: number;
  name: string;
  key: string;
  isGrouping: boolean;
  displayName?: string;
  createdAt: Date;
  updatedAt: Date;
}

export const ECategoryHistoryLogAction = {
  Created: 'created',
  Updated: 'updated',
  Deleted: 'deleted',
} as const;

type UCategoryHistoryLogAction =
  (typeof ECategoryHistoryLogAction)[keyof typeof ECategoryHistoryLogAction];

export interface ICategoryHistoryLog {
  // NB: serial id will be generated by the persistence layer
  categoryId: TEntityId;
  userId: TEntityId;
  action: UCategoryHistoryLogAction;
  diff: IDiff<ICategory>;
  note: string | null;
  createdAt: Date;
}
